// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dgb/meter.readings/application"
)

// Injectors from container.go:

func CreateApi() *ReadingApi {
	response := &Response{}
	configurationService := &application.ConfigurationService{}
	readingApi := NewApi(response, configurationService)
	return readingApi
}
