// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dgb/meter.readings/internal/application"
	"dgb/meter.readings/internal/configuration"
	"dgb/meter.readings/internal/database"
)

// Injectors from wire.go:

func CreateApi() *application.ReadingApi {
	meterEnvironment := configuration.NewMeterEnvironment()
	configurationConfiguration := configuration.NewConfig(meterEnvironment)
	response := application.NewResponse(configurationConfiguration)
	repository := database.NewRepository(configurationConfiguration)
	middleware := application.NewMiddleware(response, configurationConfiguration)
	readingApi := application.NewApi(response, configurationConfiguration, repository, middleware)
	return readingApi
}
